### PR TITLE
Development

### PR DESCRIPTION
**Pull request by contactashish13**
@silmiras I believe this is ready to be merged into master and assigned to @javiercasares for review. Hopefully this version can be released soon.

### CODE REVIEW

**Comment by contactashish13** [comment]
@silmiras any idea when the new version will be released?

**Comment by javiercasares** [comment]
@contactashish13 if it's ready for review, please change it to "Ready for Review".

Also, is there a list of changes (for the changelog)?

**Comment by contactashish13** [comment]
@javiercasares here is the changelog:

1. add "theatre=1" parameter while showing the iframe in the iframe block #38 
2. add filters for tags and cam language to the iframe block #38
3. add filters for tags and cam language, order options to the cam grid block #39 

@silmiras please test this `development` branch and mark it as ready for review for @javiercasares to proceed

**Comment by silmiras** [comment]
@javiercasares it looks fine for me, could you review it and merge it on master?

**Review by javiercasares — APPROVED** [review]
I've added some comments and security fixes. It works for me, but should be great to do a new general review, saving the form, and adding the tow blocks and playing with the options.

**Comment by javiercasares** [comment]
BTW, this should generate the v1.2.0.

**Comment by contactashish13** [comment]
@javiercasares looks good to me. @silmiras can you also give it a quick test? The test site has this branch installed.

**Pull request merged**
